# Generated by Django 5.2.8 on 2025-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Red_bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hospi', models.CharField(max_length=200)),
                ('horarios', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=100)),
                ('Contacto', models.CharField(max_length=100)),
                ('Notas', models.CharField(max_length=100)),
            ],
        ),
    ]
