# Generated by Django 5.2.8 on 2025-11-18 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canton', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_p', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lugar_campana',
            name='Campana',
        ),
        migrations.AddField(
            model_name='campana',
            name='direccion_exacta',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallerequisitos',
            name='CustomUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DetalleRequisito', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campana',
            name='Cantones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Campana', to='api.cantones'),
        ),
        migrations.AddField(
            model_name='cantones',
            name='Provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cantones', to='api.provincia'),
        ),
        migrations.DeleteModel(
            name='detalle_lugar_campana',
        ),
        migrations.DeleteModel(
            name='Lugar_campana',
        ),
    ]
