# Generated by Django 5.1.2 on 2025-11-07 19:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
       
        
        #migrations.AddField(
           # model_name='imagen_campana',
           # name='imagen',
           # field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='imagen_campana'),
           # preserve_default=False,
      #  ),
       # migrations.AddField(
          #  model_name='imagenes_publi',
            #name='imagen',
           # field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='imagen_publicacion'),
            #preserve_default=False,
       # ),
    ]
