# Generated by Django 5.1.2 on 2025-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzon',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
