# Generated by Django 5.2.8 on 2025-11-19 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251119_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='Fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campana',
            name='Fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campana',
            name='Hora_fin',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana',
            name='Hora_inicio',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
