# Generated by Django 5.1.2 on 2025-11-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_buzon_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangre',
            name='donaA',
            field=models.CharField(max_length=30),
        ),
    ]
