# Generated by Django 5.1.2 on 2025-11-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imagen_campana_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangre',
            name='frecuencia',
            field=models.CharField(default='decocnocido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sangre',
            name='poblacion',
            field=models.CharField(default=10.1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sangre',
            name='recibeDe',
            field=models.CharField(default='desconocdo', max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Urgente_Tip_Sang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgencia', models.CharField(max_length=40)),
                ('activo', models.BooleanField()),
                ('nota', models.CharField(max_length=40)),
                ('Sangre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Urgente_Tip_Sang', to='api.sangre')),
            ],
        ),
    ]
