# Generated by Django 5.1.2 on 2025-11-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sangre_frecuencia_sangre_poblacion_sangre_recibede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangre',
            name='donaA',
            field=models.CharField(default='desconocido', max_length=20),
            preserve_default=False,
        ),
    ]
