# Generated by Django 5.1.2 on 2025-11-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imagen_campana_url_and_more'),
        ('api', '0003_alter_sangre_donaa'),
    ]

    operations = [
    ]
