# Generated by Django 5.2.8 on 2025-11-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_red_bancos'),
        ('api', '0003_alter_campana_fecha_fin_alter_campana_fecha_inicio_and_more'),
    ]

    operations = [
    ]
