# Generated by Django 5.1.2 on 2025-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20251113_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Telefono',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
