# Generated by Django 5.2.8 on 2025-11-19 20:19

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20251119_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('CustomUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio_texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Frase', models.CharField(max_length=200)),
                ('Foto_P', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_Testimonio_texto')),
                ('Testimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonio_texto', to='api.testimonio')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_Testimonio_video')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Testimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonio_video', to='api.testimonio')),
            ],
        ),
    ]
