# Generated by Django 5.2.8 on 2025-11-19 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20251119_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_participacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='api.campana')),
                ('sangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sangre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_participacion',
                'ordering': ['-fecha_participacion'],
                'unique_together': {('user', 'campana')},
            },
        ),
    ]
