# Generated by Django 5.2.8 on 2025-11-24 17:14

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participacion'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio_texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Frase', models.CharField(max_length=200)),
                ('Foto_P', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_Testimonio_texto')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_Testimonio_video')),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='suscritos',
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='participacion',
            name='Numero_cedula',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='suscritos',
            name='Numero_cedula',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscritos',
            name='correo',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscritos',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_customuser_email'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='CustomUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonio_texto',
            name='Testimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonio_texto', to='api.testimonio'),
        ),
        migrations.AddField(
            model_name='testimonio_video',
            name='Testimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testimonio_video', to='api.testimonio'),
        ),
    ]
