# Generated by Django 5.1.2 on 2025-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
