# Generated by Django 5.2.8 on 2025-11-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participacion'),
        ('api', '0005_testimonio_testimonio_texto_testimonio_video'),
    ]

    operations = [
    ]
