# Generated by Django 5.2.8 on 2025-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20251120_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='Numero_cedula',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscritos',
            name='Numero_cedula',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
