# Generated by Django 5.2.8 on 2025-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_testimonio_testimonio_texto_testimonio_video_and_more'),
    ]

    operations = [
 
    ]
