# Generated by Django 5.2.8 on 2025-11-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_carusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='filtro_oscuro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carusel',
            name='mostrar_texto',
            field=models.BooleanField(default=True),
        ),
    ]
