# Generated by Django 5.2.8 on 2025-11-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_suscritos_numero_cedula_alter_suscritos_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscritos',
            name='Numero_cedula',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='correo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='suscritos',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonio_texto',
            name='Frase',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonio_texto',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
    ]
