# Generated by Django 5.2.8 on 2025-11-17 16:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_carusel_filtro_oscuro_carusel_mostrar_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar_campana',
            name='Campana',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Lugar_campana', to='api.campana'),
            preserve_default=False,
        ),
    ]
