# Generated by Django 5.2.8 on 2025-11-17 19:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_galeria_remove_campana_lugar_campana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_g', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_g')),
            ],
        ),
        migrations.RemoveField(
            model_name='campana',
            name='Lugar_campana',
        ),
    ]
