# Generated by Django 5.2.8 on 2025-11-18 00:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_galeria_remove_campana_lugar_campana_and_more'),
    ]

    operations = [
        
      
        migrations.CreateModel(
            name='detalle_lugar_campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_lugar_campana', to='api.campana')),
                ('Lugar_campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_lugar_campana', to='api.lugar_campana')),
            ],
        ),
    ]
